version: '3'

services:
  db:
    image: postgres

    restart: always

    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: task-manager
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass123
